### ISSUE TITLE
Create mailinglist icon and remove text field

### ISSUE THREAD

**Issue by leo** [hakkens/phonebloks#1]
An icon will be added instead - @davehakkens will create it.

**Comment by leo** [comment]
I thought we already talked about this, @davehakkens. Are you sure that you want to remove the field in favor of a tiny icon?

As I said, the reason why I would keep it is because the envelope icon might be misguiding (since it's usually used as a "Contact" icon). I also think that the mail input fits nicely into the footer, otherwise there would be a lot of whitespace.

What do you think, @davehakkens?

**Comment by davehakkens** [comment]
Yep we did. However had some thoughts and a good look at it.

Since we are not that active with sending out mails it shouldn't be that dominate on every page. The more stuff we put in the footer the less focus there is on the things that matter to us.

Keep the envelop icon for now. Meanwhile I will work on a more communicative icon
