### ISSUE TITLE
Those other company icons should also be linked

### ISSUE THREAD

**Issue by leo** [hakkens/phonebloks#4]
And therefore also open a popup (looks the same as in the "Friends" section) on click.

**Comment by leo** [comment]
@davehakkens Should those other company-logos also open a Popup on click? I think no, right? I mean, there are's a huge number of those.

**Comment by davehakkens** [comment]
I'm afraid it should. We want to share a couple of sentences about each logo to explain excactly what they are doing. No image. However if you think there are better ways to show those sentences then a popup i'm open for it.   

Also, we wont have as much logos as in the example. Probably between 30-60, still a rough estimate since we are wokting on gathering those logos.

**Comment by leo** [comment]
You said "No image", but I thought it's better to implement it since the user needs to know which company he's currently viewing, right? :blush:

**Comment by davehakkens** [comment]
well done!
